language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
before_install:
  - git clone https://github.com/flutter/flutter.git -b beta
install:
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
